// slab

type=top
type=bottom

// snow

layers=1
layers=2
layers=3
layers=4
layers=5
layers=6
layers=7
layers=8

// fence

:north=false:south=false:east=false:west=false
:north=true:south=false:east=false:west=false
:north=false:south=false:east=false:west=true
:north=true:south=false:east=false:west=true
:north=false:south=true:east=false:west=false
:north=true:south=true:east=false:west=false
:north=false:south=true:east=false:west=true
:north=true:south=true:east=false:west=true
:north=false:south=false:east=true:west=false
:north=true:south=false:east=true:west=false
:north=false:south=false:east=true:west=true
:north=true:south=false:east=true:west=true
:north=false:south=true:east=true:west=false
:north=true:south=true:east=true:west=false
:north=false:south=true:east=true:west=true
:north=true:south=true:east=true:west=true

// wall

:north=none:south=none:east=none:west=none:up=true
:north=low:south=none:east=none:west=none:up=true
:north=tall:south=none:east=none:west=none:up=true
:north=none:south=none:east=none:west=low:up=true
:north=low:south=none:east=none:west=low:up=true
:north=tall:south=none:east=none:west=low:up=true
:north=none:south=none:east=none:west=tall:up=true
:north=low:south=none:east=none:west=tall:up=true
:north=tall:south=none:east=none:west=tall:up=true
:north=none:south=low:east=none:west=none:up=true
:north=low:south=low:east=none:west=none:up=true
:north=tall:south=low:east=none:west=none:up=true
:north=none:south=low:east=none:west=low:up=true
:north=low:south=low:east=none:west=low:up=true
:north=tall:south=low:east=none:west=low:up=true
:north=none:south=low:east=none:west=tall:up=true
:north=low:south=low:east=none:west=tall:up=true
:north=tall:south=low:east=none:west=tall:up=true
:north=none:south=tall:east=none:west=none:up=true
:north=low:south=tall:east=none:west=none:up=true
:north=tall:south=tall:east=none:west=none:up=true
:north=none:south=tall:east=none:west=low:up=true
:north=low:south=tall:east=none:west=low:up=true
:north=tall:south=tall:east=none:west=low:up=true
:north=none:south=tall:east=none:west=tall:up=true
:north=low:south=tall:east=none:west=tall:up=true
:north=tall:south=tall:east=none:west=tall:up=true
:north=none:south=none:east=low:west=none:up=true
:north=low:south=none:east=low:west=none:up=true
:north=tall:south=none:east=low:west=none:up=true
:north=none:south=none:east=low:west=low:up=true
:north=low:south=none:east=low:west=low:up=true
:north=tall:south=none:east=low:west=low:up=true
:north=none:south=none:east=low:west=tall:up=true
:north=low:south=none:east=low:west=tall:up=true
:north=tall:south=none:east=low:west=tall:up=true
:north=none:south=low:east=low:west=none:up=true
:north=low:south=low:east=low:west=none:up=true
:north=tall:south=low:east=low:west=none:up=true
:north=none:south=low:east=low:west=low:up=true
:north=low:south=low:east=low:west=low:up=true
:north=tall:south=low:east=low:west=low:up=true
:north=none:south=low:east=low:west=tall:up=true
:north=low:south=low:east=low:west=tall:up=true
:north=tall:south=low:east=low:west=tall:up=true
:north=none:south=tall:east=low:west=none:up=true
:north=low:south=tall:east=low:west=none:up=true
:north=tall:south=tall:east=low:west=none:up=true
:north=none:south=tall:east=low:west=low:up=true
:north=low:south=tall:east=low:west=low:up=true
:north=tall:south=tall:east=low:west=low:up=true
:north=none:south=tall:east=low:west=tall:up=true
:north=low:south=tall:east=low:west=tall:up=true
:north=tall:south=tall:east=low:west=tall:up=true
:north=none:south=none:east=tall:west=none:up=true
:north=low:south=none:east=tall:west=none:up=true
:north=tall:south=none:east=tall:west=none:up=true
:north=none:south=none:east=tall:west=low:up=true
:north=low:south=none:east=tall:west=low:up=true
:north=tall:south=none:east=tall:west=low:up=true
:north=none:south=none:east=tall:west=tall:up=true
:north=low:south=none:east=tall:west=tall:up=true
:north=tall:south=none:east=tall:west=tall:up=true
:north=none:south=low:east=tall:west=none:up=true
:north=low:south=low:east=tall:west=none:up=true
:north=tall:south=low:east=tall:west=none:up=true
:north=none:south=low:east=tall:west=low:up=true
:north=low:south=low:east=tall:west=low:up=true
:north=tall:south=low:east=tall:west=low:up=true
:north=none:south=low:east=tall:west=tall:up=true
:north=low:south=low:east=tall:west=tall:up=true
:north=tall:south=low:east=tall:west=tall:up=true
:north=none:south=tall:east=tall:west=none:up=true
:north=low:south=tall:east=tall:west=none:up=true
:north=tall:south=tall:east=tall:west=none:up=true
:north=none:south=tall:east=tall:west=low:up=true
:north=low:south=tall:east=tall:west=low:up=true
:north=tall:south=tall:east=tall:west=low:up=true
:north=none:south=tall:east=tall:west=tall:up=true
:north=low:south=tall:east=tall:west=tall:up=true
:north=tall:south=tall:east=tall:west=tall:up=true
:north=none:south=none:east=low:west=low:up=false
:north=none:south=none:east=tall:west=tall:up=false 
:north=low:south=low:east=none:west=none:up=false  
:north=tall:south=tall:east=none:west=none:up=false 
:north=low:south=low:east=tall:west=tall:up=false 
:north=tall:south=tall:east=low:west=low:up=false 
:north=tall:south=tall:east=tall:west=tall:up=false 
:north=low:south=low:east=low:west=low:up=false
